### ISSUE TITLE
Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by burtonrj** [chasemc/electricShine#294]
When running electrify on Ubuntu 18.04 I get the following error:

`Error in list.files(rlang_path, pattern = "Rscript") : 
  invalid 'path' argument`

I think this is because in install_r.R `rlang_path <- NULL` and then a value is assigned if os == "win" or os == "mac" but no condition is set for "unix". 

Does electricShine not support development on unix machines? Happy to spin up a VM if not, also happy to make a Pull request if you're busy.

Thanks.

**Comment by chasemc** [comment]
Yeah, I didn't spend time implementing it as I hadn't/haven't seen much expressed interest so far. 
I'm pretty busy right now so I'm open to pull requests. Linux is unfortunately a bit complicated because installing a decent number of packages (at least ones I use) can be a bit more of a hassle due to R's `install.packages` not installing non-R dependencies.   

Most Linux users I know seem not to be scared of using the command line, so if this is a one-off project for you I would suggest writing a dockerfile for linux users to use, than investing a lot of time getting a bomb-proof Linux implementation. (if you haven't used docker alongside Shiny, a good place to start would be: https://thinkr-open.github.io/golem/reference/dockerfiles.html)

**Comment by burtonrj** [comment]
This is a one off project. I've had a little play and I was met with a lot of headaches. I've spoken to end users and they are nearly almost all Windows users except for one Mac. So I'm the odd one out using Ubuntu.

I've spun up a VM and generated a build in Win10. Thanks for taking the time to answer. I really appreciate this library you've put together!
